modLoader = "kotlinforforge"
loaderVersion = "[3,)"
license = "GNU GPL 3.0"
issueTrackerURL = "https://github.com/KodingDev/islander/issues"

[[mods]]
modId = "islander"
version = "${version}"
displayName = "Islander"
displayURL = "https://koding.dev"
logoFile = "icon.png"
authors = "KodingDev"
displayTest = "IGNORE_ALL_VERSION"

description = '''
A companion mod to MCC Island!
'''

# Depend on Forge
[[dependencies.islander]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "CLIENT"

# Depend on Minecraft
[[dependencies.islander]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"